CREATE TABLE password_reset_tokens
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    token_hash  VARCHAR(255) NOT NULL UNIQUE,
    user_id     BIGINT       NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    expiry_date TIMESTAMP    NOT NULL,
    used_at     TIMESTAMP,
    CONSTRAINT fk_reset_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_reset_token ON password_reset_tokens (token_hash);
CREATE INDEX idx_reset_user ON password_reset_tokens (user_id);
CREATE INDEX idx_reset_expiry ON password_reset_tokens (expiry_date);