CREATE TABLE refresh_tokens
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    token       VARCHAR(255) UNIQUE,
    user_email  VARCHAR(255),
    expiry_date TIMESTAMP,
    revoked_at  TIMESTAMP
);