CREATE TABLE refresh_tokens
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    token       VARCHAR(255) UNIQUE,
    user_id  BIGINT ,
    expiry_date TIMESTAMP,
    revoked_at  TIMESTAMP
);