server:
  port: 8083

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/grocery_user
    username: postgres
    password: Naveen@70
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,audit
  endpoint:
    health:
      show-details: always

app:
  jwt:
    secret: dev-secret-for-grocerymart-14052000
    expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  paths-to-match:
    - /api/**
